### ISSUE TITLE
jnp.vectorize -> vmap

### ISSUE THREAD

**Issue by lockwo** [lockwo/distreqx#12]
This occurs in several places in the code base, I much prefer vmap to vectorize as its more common and more understandable (vectorize is just a wrapper on vmap anyway)

**Comment by ramyaakella** [comment]
So , If I understand this correctly , the vectorize method needs to be replaced with vmap , in all 3 occurrences of the code.
I would like to work on this issue 
Also, what would be a good way to test if the functionality is still working well after the changes ?

**Comment by Mews** [comment]
@ramyaakella you can run the tests using pytest
Take a look at https://github.com/lockwo/distreqx/blob/main/CONTRIBUTING.md

**Comment by lockwo** [comment]
Yes exactly. Replace those 3 occurrences (should be probably <10 LoC change). The same tests should still pass (since the functionality is unchanged), but I'm always supportive of adding more tests as well
