### ISSUE TITLE
Can't run unit tests: `pytest: error: unrecognized arguments: --jaxtyping-packages...`

### ISSUE THREAD

**Issue by Mews** [lockwo/distreqx#19]
On my windows 11 machine, I can't run the tests for this library.
When I try doing `pytest tests` I get the following error message:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --jaxtyping-packages=distreqx,beartype.beartype(conf=beartype.BeartypeConf(strategy=beartype.BeartypeStrategy.On))
  inifile: C:\Users\joaoc\OneDrive\Ambiente de Trabalho\venv\distreqx\pyproject.toml
  rootdir: C:\Users\joaoc\OneDrive\Ambiente de Trabalho\venv\distreqx
``` 

**Steps to replicate**
1. Create a virtual environment using `py -m venv .`
2. Clone repository using `git clone https://github.com/lockwo/distreqx` and `cd distreqx`
3. Install test requirements using `pip install -r tests/requirements.txt`
4. Run the command `pytest tests`

**Comment by lockwo** [comment]
Is this using WSL?

**Comment by Mews** [comment]
Nope. Can you only run the tests on a Linux machine?

**Comment by lockwo** [comment]
Jax used to have pretty weak support for windows, not sure if that’s changed. That being said this isn’t erroring on a Jax thing but a pytest thing. Did you also run pip install -e . in distreqx in addition to installing the testing requirements?
