### ISSUE TITLE
Add normalizing flow example

### ISSUE THREAD

**Issue by lockwo** [lockwo/distreqx#8]

**Comment by lockwo** [comment]
Yes, I figured MaskedCoupling would be a prerequisite for this issue. It is on the checklist (https://github.com/lockwo/distreqx/issues/5), and while not all of them will be done pre-release, MaskedCoupling will be. I don't have an exact timeline on this but I was planning on taking a look at the NF bijectors this week. If you want to do it sooner, you are also welcome to open a PR

**Comment by homerjed** [comment]
Yeah I will have a look also, but not sure exactly when, I guess it shouldn't be hard but I need to familiarize with `distreqx` :)
